### ISSUE TITLE
Reproduction issue

### ISSUE THREAD

**Issue by CS123n** [sWizad/split-diffusion#1]
In Figure 1 of your paper, you show the problem of PLMS. However, I cannot use your code to reproduce this problem. Here are some 10-step PLMS4 results using c128, which look much better than those in the paper.
![img-24](https://user-images.githubusercontent.com/102355527/224600841-006012a3-0dcd-480c-9377-7cb68af04bc6.png)![img-25](https://user-images.githubusercontent.com/102355527/224600847-0a6b0ee7-2a22-4598-91b7-5000f047542e.png)![img-22](https://user-images.githubusercontent.com/102355527/224600848-1c0b8ade-8d66-4e2c-976e-a9d0f5f91189.png)![img-23](https://user-images.githubusercontent.com/102355527/224600851-1fc68aa8-ec93-4f5c-a2e4-76985f98cc0c.png)

**Comment by sWizad** [comment]
Regarding Figure 1 in our paper, we used the unconditional diffusion model 256 (u256) to create the PLMS problem. This model is known to be more unstable than the conditional model, which may explain why you are having difficulty reproducing the problem using our code.

To reproduce the problem, you could try reducing the number of sampling steps or using a larger guidance scale. Alternatively, you could try using the u256 model that we used in our paper.

I hope this helps.
